---
title: "RentCrawler"
author: "Luke Fan"
date: "2017/4/26"
output: html_document
---


## 從資料裡讀取後填補資料
```{r}
library(rvest)
library(stringr)
datas = read.csv("拜託給我房子.csv", header = TRUE, sep = ",", fileEncoding = "big5")
datas = datas[!is.na(datas$租金),]
df = data.frame()
i = 0
repeat{
  url = datas$網址
  ##url = 'https://rent.591.com.tw/rent-detail-5128011.html'
  rent_url = read_html(url) 
  ## 因資料裡有其他網站之Data
  if(grepl("rent.591", url)){
    ##正規表達法 . = 萬用字元
    model = rent_url %>% html_nodes(".attr") %>% html_text() %>% str_match(.,'現況.:.(.+)') %>% .[,2] %>% str_trim()
    price = rent_url %>% html_nodes(".price") %>% html_nodes("i") %>% html_text() %>% str_trim()
    address = rent_url %>% html_nodes(".addr") %>% html_text() 
    landlord = rent_url %>% html_nodes(".avatarRight") %>% html_nodes("i") %>%html_text()
    ##利用正規表達法取出電話
    mobile = str_match(rent_url,'<span class="num">(.+)</span>')[,2]
  }
  
  tem = data.frame(房型 = model,價錢 = price,地址 = address, 房東 = landlord, 電話 = mobile )
  df = rbind(df,tem)
  if(length(rent_title) == 0 ){
    break
  }else{
    i = i + 1
  }
  
}
#寫入txt裡
#write(rent_All[-1],file = "movie.txt",append = TRUE)
```


```{r}
library(rvest)
#宣告一個function
grabDatas = function(pattern,keyword){
  url = paste0('https://rent.591.com.tw/new/?kind=1&region=1&pattern=',pattern,'&keywords=',keyword,'&section=12')
  page_url = read_html(url) 
  title = page_url %>% html_nodes(".infoContent") %>% html_nodes("h3") %>%  html_nodes("a") %>% html_text() %>% .[. != ""]
  rent_urls = page_url %>% html_nodes(".infoContent") %>% html_nodes("h3") %>%  html_nodes("a") %>%  html_attr("href") %>% .[. != "javascript:;"]
  ## 字串處理-網址
  library(stringr)
  rent_urls = paste0("https:",str_trim(str_match(rent_urls,'\n(.+)\n')[,2]))
  
  ##個別處理url
  df = data.frame()
  for (rent_url in rent_urls) {
    ##正規表達法 . = 萬用字元
    url = read_html(rent_url)
    title = url %>% html_nodes(".houseInfoTitle") %>% html_text()
    now = url %>% html_nodes(".attr") %>% html_text() %>% str_match(.,'現況.:.(.+)') %>% .[,2] %>% str_trim()
    if(grepl("權狀坪數", url)){
      model = url %>% html_nodes(".attr") %>% html_text() %>% str_match(.,'格局.:.(.+).坪數.') %>% .[,2] %>% str_match(.,'(.+)坪數.')  %>% .[,2] %>% str_trim()
    }else{
      model = url %>% html_nodes(".attr") %>% html_text() %>% str_match(.,'格局.:.(.+)坪數.') %>% .[,2] %>% str_trim()
    }
    price = url %>% html_nodes(".price") %>% html_nodes("i") %>% html_text() %>% str_trim()
    address = url %>% html_nodes(".addr") %>% html_text() 
    landlord = url %>% html_nodes(".avatarRight") %>% html_nodes("i") %>%html_text()
    ##利用正規表達法取出電話
    mobile = str_match(url,'<span class="num">(.+)</span>')[,2]
    
    tem = data.frame(新上架 = "",價錢 = price, 格局 = model, 房東 = landlord, 電話 = mobile, 地址 = address, 網址 = rent_url,標題 = title)
    df = rbind(df,tem)
  }
  return(df)
}


#patterns =>幾房
patterns = c(3,4)
keywords = c("景美","萬隆")
df = data.frame()
for (keyword in keywords) {
  for (pattern in patterns) {
    df = rbind(df,grabDatas(pattern,keyword))
    Sys.sleep(1)
  }
}



```


## 檢測是否為新上架
```{r}
#移除第一欄值
datas = read.csv("拜託給我房子_R.csv", header = TRUE, sep = ",")[,-1]
datas$新上架 = "" 
df$新上架 = "新"
total = rbind(datas, df)
total = total[!duplicated(total[,"標題"]),]

write.csv(df,file = "拜託給我房子_R.csv")
```

#將DataFrame 轉換成tabel
```{r}
library(xtable)
news_Rent = total[total$新上架 == "新",]
  msg <- mime_part(paste('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0
  Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>', print(xtable(news_Rent), type = 'html'), ',</body>
  </html>'))
```


# 當有新房屋上架寄email通知
# Send Gmail from Gmail
## 需打開Google的低安全應用程式
```{r}
news_Rent = total[total$新上架 == "新",-1]

library(mailR)
  
sender <- "sender@gmail.com"
recipients <- c("recipients@gmail.com")
user <- "user@gmail.com"
passwd <- "Password"

send.mail(from = sender,
          to = recipients,
          subject = "New Rent",
          body = msg,
          html = TRUE,
          encoding = "utf-8",
          smtp = list(host.name = "smtp.gmail.com", port = 465, 
                      user.name = user,            
                      passwd = passwd, 
                      ssl = TRUE),
                 authenticate = TRUE,
                 send = TRUE)
```

